# Default values for focus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#Deploynment values

app: focus
replicas: 2
ECR_REGISTRY:
IMAGE_TAG: 



service:
  type: ClusterIP
  port: 80
  target_port: 80
  protocol: TCP