# Default values for focus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#Deploynment values !

app: focus
replicas: 2
ECR_REGISTRY: 351554785424.dkr.ecr.us-east-1.amazonaws.com
IMAGE_TAG: 54
deployment_name: focus-deployment


service:
  type: LoadBalancer
  port: 80
  target_port: 80
  protocol: TCP
  service_name: focus-service