apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: focus-deployment
  namespace: dev        # <-- Deploys into 'dev'
  labels:
    app: focus
spec:
  replicas: 2
  selector:
    matchLabels:
      app: focus
  template:
    metadata:
      labels:
        app: focus
    spec:
      containers:
        - name: focus
          image: focus-timer
          ports:
            - containerPort: 80
